"""Normalized expert risk scores from ``Back бота Valor V10.xlsx``."""

from typing import Any


def _share(
    identifier: str,
    issuer: str,
    sector: str,
    company_type: str | None,
    inflation: int | None,
    geopolitical: int | None,
    domestic_political: int | None,
    debt: int | None,
    currency: int | None,
    minority_shareholder: int | None,
) -> dict[str, Any]:
    return {
        "asset_type": "share",
        "identifier": identifier,
        "issuer": issuer,
        "sector": (sector.strip() or None) if sector != "?" else None,
        "company_type": company_type,
        "bond_kind": None,
        "currency": "RUB",
        "coupon_type": None,
        "inflation_risk": inflation,
        "geopolitical_risk": geopolitical,
        "domestic_political_risk": domestic_political,
        "debt_risk": debt,
        "currency_risk": currency,
        "minority_shareholder_risk": minority_shareholder,
        "source_sheet": "Отбор акций",
    }


def _bond(
    identifier: str,
    bond_kind: str,
    issuer: str,
    currency: str,
    coupon_type: str,
    inflation: int,
    geopolitical: int,
    domestic_political: int,
    debt: int,
    currency_risk: int,
    minority_shareholder: int,
) -> dict[str, Any]:
    return {
        "asset_type": "bond",
        "identifier": identifier,
        "issuer": issuer.strip() or "—",
        "sector": None,
        "company_type": None,
        "bond_kind": bond_kind,
        "currency": currency,
        "coupon_type": coupon_type,
        "inflation_risk": inflation,
        "geopolitical_risk": geopolitical,
        "domestic_political_risk": domestic_political,
        "debt_risk": debt,
        "currency_risk": currency_risk,
        "minority_shareholder_risk": minority_shareholder,
        "source_sheet": "Отбор бондов",
    }


VALOR_ASSET_RISKS: list[dict[str, Any]] = [
    _share("LKOH", "ЛУКОЙЛ", "Нефтегаз", "Дивидендная", 1, 6, 3, 1, 1, 1),
    _share("SBER", "Сбербанк", "Банкинг", "Дивидендная", 2, 6, 2, 3, 4, 1),
    _share("GAZP", "ГАЗПРОМ ао", "Нефтегаз", "Дивидендная", 1, 6, 2, 3, 1, 5),
    _share("YDEX", "ЯНДЕКС", "IT", "Роста", 2, 4, 3, 2, 5, 2),
    _share("T", "Т-Техно ао", "Банкинг", "Роста", 2, 4, 3, 4, 4, 1),
    _share("TATN", "Татнфт 3ао", "Нефтегаз", "Дивидендная", 1, 5, 4, 1, 1, 1),
    _share("NVTK", "Новатэк ао", "СПГ", "Роста", 1, 6, 2, 1, 1, 4),
    _share("GMKN", "ГМКНорНик", "Металлурги", "Дивидендная", 1, 5, 2, 4, 2, 4),
    _share("OZON", "Озон", "Маркетплейс", "Роста", 3, 3, 4, 3, 3, 2),
    _share("X5", "КЦ ИКС 5", "Ритейл", "Дивидендная", 2, 2, 3, 2, 3, 1),
    _share("PLZL", "Полюс", "Золотодобыча", "Дивидендная", 1, 4, 3, 1, 1, 6),
    _share("ROSN", "Роснефть", "Нефтегаз", "Дивидендная", 1, 6, 1, 3, 1, 2),
    _share("VTBR", "ВТБ ао", "Банкинг", "Дивидендная", 2, 6, 4, 4, 4, 6),
    _share("SNGSP", "Сургнфгз-п", "Нефтегаз", "Дивидендная", 1, 6, 2, 1, 1, 2),
    _share("SNGS", "Сургнфгз", "Нефтегаз", "Дивидендная", 1, 6, 2, 1, 1, 2),
    _share("HEAD", "Хэдхантер", "IT", "Роста", 2, 1, 4, 1, 2, 2),
    _share("MOEX", "МосБиржа", "", "Роста", 2, 4, 2, 1, 2, 1),
    _share("MTSS", "МТС-ао", "Провайдеры связи", "Дивидендная", 3, 1, 4, 4, 3, 1),
    _share("IRAO", "ИнтерРАОао", "Электропровайдеры", "Дивидендная", 3, 5, 1, 1, 3, 4),
    _share("CBOM", "МКБ ао", "Банкинг", None, 2, 4, 4, 5, 4, 3),
    _share("CHMF", "СевСт-ао", "Металлурги", "Дивидендная", 2, 6, 3, 1, 3, 2),
    _share("RUAL", "РУСАЛ ао", "Металлурги", "Дивидендная", 2, 6, 5, 4, 4, 4),
    _share("NLMK", "НЛМК ао", "Металлурги", "Дивидендная", None, None, None, 1, 2, None),
    _share("DOMRF", "ДОМ.РФ", "Банкинг", "Роста", 2, 4, 2, 3, 4, 1),
    _share("PHOR", "ФосАгро ао", "Удобрения", "Дивидендная", 1, 5, 2, 3, 2, 1),
    _share("SVCB", "Совкомбанк", "Банкинг", "Роста", None, 4, None, 4, None, 3),
    _share("RTKM", "Ростел -ао", "Провайдеры связи", "Роста", 2, 2, None, None, 4, 3),
    _share("AFLT", "Аэрофлот", "Авиаперевозки", "Дивидендная", 3, 6, 5, 5, 5, 5),
    _share("MAGN", "ММК", "Металлурги", "Дивидендная", None, 5, None, None, None, 2),
    _share("TRNFT", "Транснф ап", "Транспортировка нефти и газа", "Дивидендная", 2, 6, 1, 1, 3, 1),
    _share("MDMG", "MDMG-ао", "Мед. Компания", "Роста", 2, 1, 2, 2, 3, 1),
    _share("ALRS", "АЛРОСА ао", "Алмазы", "Роста", None, 5, None, None, None, 4),
    _share("LENT", "Лента ао", "Ритейл", "Роста", 2, 2, 4, 2, 3, 3),
    _share("BSPB", "БСП ао", "Банкинг", "Роста", 2, 4, 3, 2, 4, 1),
    _share("FLOT", "Совкомфлот", "Флот", "Дивидендная", None, 5, None, 2, None, 3),
    _share("RAGR", "Русагро", "Агрохолдинг", "Дивидендная", 2, 4, 1, 3, 2, 2),
    _share("AFKS", "Система ао", "Инвест. Компания", "Роста", None, None, None, 4, None, 3),
    _share("CNRU", "iЦиан", "IT", "Роста", 3, 1, 3, 1, 4, 2),
    _share("POSI", "iПозитив", "IT", "Роста", 3, 4, 3, 4, 2, 5),
    _share("UGLD", "ЮГК", "Золотодобыча", "Роста", 2, 4, 1, 4, 2, 5),
    _share("VKCO", "МКПАО ВК", "IT", "Роста", 3, 2, 3, 5, 3, 6),
    _share("RENI", "Ренессанс", "Страхование", "Роста", 3, 2, 4, 1, 3, 1),
    _share("MSNG", "+МосЭнерго", "Электропровайдеры", "Дивидендная", 4, 4, 2, 1, 3, 2),
    _bond("RU000A108EH4", "ОФЗ", "—", "RUB", "Фикс", 5, 1, 1, 1, 5, 1),
    _bond("RU000A108EF8", "ОФЗ", "—", "RUB", "Фикс", 5, 1, 1, 1, 5, 1),
    _bond("RU000A106E90", "ОФЗ", "—", "RUB", "Фикс", 5, 1, 1, 1, 5, 1),
    _bond("RU000A108EE1", "ОФЗ", "—", "RUB", "Фикс", 5, 1, 1, 1, 5, 1),
    _bond("RU000A10D533", "ОФЗ", "—", "RUB", "Фикс", 5, 1, 1, 1, 5, 1),
    _bond("RU000A10BVH7", "ОФЗ", "—", "RUB", "Фикс", 5, 1, 1, 1, 5, 1),
    _bond("RU000A0JV4P3", "ОФЗ", "—", "RUB", "Перемен", 5, 1, 1, 1, 5, 1),
    _bond("RU000A0JV4N8", "ОФЗ", "—", "RUB", "Перемен", 5, 1, 1, 1, 5, 1),
    _bond("RU000A0JV4Q1", "ОФЗ", "—", "RUB", "Перемен", 5, 1, 1, 1, 5, 1),
    _bond("RU000A1025A7", "ОФЗ", "—", "RUB", "Перемен", 5, 1, 1, 1, 5, 1),
    _bond("RU000A102A49", "ОФЗ", "—", "RUB", "Перемен", 5, 1, 1, 1, 5, 1),
    _bond("RU000A0GN9A7", "ОФЗ", "—", "RUB", "Аморт", 5, 1, 1, 1, 5, 1),
    _bond("RU000A10AXW4", "КОРП", "Сибур", "USD", "Фикс", 3, 1, 2, 3, 1, 1),
    _bond("RU000A10CRC4", "КОРП", "Норникель", "USD", "Фикс", 3, 1, 2, 3, 1, 1),
    _bond("RU000A10FC62", "КОРП", "Норникель", "CNY", "Фикс", 4, 1, 2, 3, 1, 1),
    _bond("RU000A10EER6", "КОРП", "Фосагро", "CNY", "Фикс", 4, 1, 2, 2, 1, 1),
    _bond("RU000A10BK17", "КОРП", "Газпромнефть", "RUB", "Фикс", 5, 1, 2, 1, 5, 1),
    _bond("RU000A10DS74", "КОРП", "Сбер", "RUB", "Фикс", 5, 1, 2, 2, 5, 1),
    _bond("RU000A10C618", "КОРП", "Магнит", "RUB", "Фикс", 5, 1, 2, 3, 5, 1),
    _bond("RU000A10DZW3", "КОРП", "РЖД", "RUB", "Фикс", 5, 1, 2, 3, 5, 1),
    _bond("RU000A106ZL5", "КОРП", "РЖД", "RUB", "Перемен", 5, 1, 2, 3, 5, 1),
    _bond("RU000A106375", "КОРП", "Газпром", "RUB", "Перемен", 5, 1, 2, 2, 5, 1),
    _bond("RU000A1069N8", "КОРП", "Норникель", "RUB", "Перемен", 5, 1, 2, 3, 5, 1),
    _bond("RU000A106K43", "КОРП", "РЖД", "RUB", "Перемен", 5, 1, 2, 3, 5, 1),
    _bond("RU000A1041Q0", "КОРП", "ДОМ РФ", "RUB", "Перемен", 5, 1, 2, 1, 5, 1),
    _bond("RU000A10EW93", "КОРП", "ВТБ", "RUB", "Амортизация", 5, 1, 3, 2, 5, 1),
    _bond("RU000A10D4F1", "КОРП", "Россети", "RUB", "Амортизация", 5, 1, 1, 1, 5, 1),
]
